#!/usr/bin/env bash
# Configured nginx server for custom header
sudo apt-get -y install nginx

FILE=/etc/nginx/sites-available/default

sudo sed -i "23i \\\tadd_header X-Served-By \$hostname;" $FILE

sudo service nginx restart
