#!/usr/bin/env bash
#start/stop/restart a process
if [ "$1" == "start" ]
then
    sudo touch /tmp/my_process
    sudo touch /var/run/my_process.pid
    echo $$ >> sudo /var/run/my_process.pid
    echo "manage_my_process started"
elif [ "$1" == "stop" ]
then
    echo "manage_my_process stopped"
    sudo pkill -f ./manage_my_process
    sudo rm /var/run/my_process.pid
elif [ "$1" == "restart" ]
then
    sudo rm /var/run/my_process.pid
    sudo touch /tmp/my_process
    sudo touch /var/run/my_process.pid
    echo $$ >> suod /var/run/my_process.pid
    echo "manage_my_process restarted"
else
    echo "Usage: manage_my_process {start|stop|restart}"
fi
