#!/usr/bin/env bash
#displays the content of /etc/passwd
FILE="/etc/passwd"
while IFS='' read -r line
do
    USERNAME=$(echo "$line" | cut -d ':' -f1)
    GROUP_ID=$(echo "$line" | cut -d ':' -f4)
    HOME_DIRECTORY=$(echo "$line" | cut -d ':' -f6)
    COMMAND_SHELL=$(echo "$line" | cut -d ':' -f7)
    PASSWORD=$(echo "$line" | cut -d ':' -f2)
    USER_ID=$(echo "$line" | cut -d ':' -f3)
    USER_ID_INFO=$(echo "$line" | cut -d ':' -f5)
    echo "The user $USERNAME is part of the $GROUP_ID gang, lives in $HOME_DIRECTORY and rides $COMMAND_SHELL. $USER_ID's place is protected by the passcode $PASSWORD, more info about the user here: $USER_ID_INFO"
done < "$FILE"
