#!/usr/bin/env bash
# This script displays "Holberton School" 10 times
# on the 4th says 'bad luck'
# on the 8th says 'good luck'
START=1
END=20
while (( START <= END ))
do
    case $START in
	5)
	echo "bad luck from China"
	;;
	10)
	echo "bad luck from Japan"
	;;
	18)
	echo "bad luck from Italy"
	;;
    esac
    echo "$START"
    ((START = START + 1))
done
