#!/usr/bin/env bash
#Script displays content of current directory, in a list format
#Only part of the name after the 1st dash is displayed
command=$(ls)
for i in $command ; do
    echo "$i" | cut -d '-' -f2
done
