#!/usr/bin/env bash
#refigures nginx config file to chagne user to nginx
FILE=/etc/nginx/nginx.conf
sudo chmod 644 $FILE
sudo sed -i "1i user nginx;" $FILE
sudo sed 's/80/8080' /etc/nginx/sites-enabled/default
kill -9 "$(pidof apache2)"
sudo service apache2 stop
sudo service nginx restart
